#!/usr/bin/env python

import roslib
roslib.load_manifest('rospilot')
import rospilot  # noqa  need this line because it sets up the sys.path
import rospy
from vlc_server import server
import std_srvs.srv
from optparse import OptionParser
import os
import os.path
import shutil
import tempfile
import threading
from datetime import datetime


class VlcNode:
    def __init__(self, mrl, media_path):
        self.recorder = server.VlcRecorder(mrl=mrl, mux="ogg")
        self.media_path = os.path.expanduser(media_path)
        self.tempfile = None
        self.lock = threading.RLock()

        if not os.path.exists(self.media_path):
            os.makedirs(self.media_path)

        rospy.init_node("ros_vlc")
        rospy.Service('start_record',
                      std_srvs.srv.Empty,
                      self.handle_start_record)
        rospy.Service('stop_record',
                      std_srvs.srv.Empty,
                      self.handle_stop_record)

    @classmethod
    def media_time(self):
        return datetime.today().strftime("%Y-%m-%d_%H%M%S")

    def handle_start_record(self, empty_message):
        with self.lock:
            if self.tempfile is not None:
                self.handle_stop_record(None)
            (fd, self.tempfile) = tempfile.mkstemp()
            os.close(fd)

            self.recorder.start_record(self.tempfile)
            return std_srvs.srv.EmptyResponse()

    def handle_stop_record(self, empty_message):
        with self.lock:
            self.recorder.stop_record()
            date = VlcNode.media_time()
            path = "%s/%s.ogg" % (self.media_path, date)
            i = 1
            while os.path.exists(path):
                path = "%s/%s_%d.ogg" % (self.media_path, date, i)
                i += 1
            shutil.move(self.tempfile, path)
            self.tempfile = None
            return std_srvs.srv.EmptyResponse()

    # NOTE: Not tested.
    def handle_take_snapshot(self, empty_message):
        date = VlcNode.media_time()
        path = "%s/%s.png" % (self.media_path, date)
        i = 1
        while os.path.exists(path):
            path = "%s/%s_%d.png" % (self.media_path, date, i)
            i += 1
        self.recorder.take_snapshot(path, 640, 480)

    def run(self):
        rospy.loginfo("Vlc Node Initialized and waiting...")
        rospy.spin()

if __name__ == '__main__':
    parser = OptionParser("ros_vlc.py <options>")
    parser.add_option(
        "--media_path",
        dest="media_path",
        help="Directory to store media generated by drone",
        default="/tmp")
    parser.add_option(
        "--input_stream",
        dest="input_stream",
        help="Media Resource Location of incoming stream",
        default="http://0.0.0.0:8080/stream?topic=/camera/image_raw/compressed")
    (opts, args) = parser.parse_args()
    node = VlcNode(
        mrl=opts.input_stream,
        media_path=opts.media_path)
    node.run()
